[Loom 1.6] Fix NeoForge mapping issues with NeoForge interfaces
architectury/architectury-loom pull request #207
Opened 2024-04-23 07:26 UTC by Jab125

Closes #206 

This pull request fixes any issues introduced with https://github.com/neoforged/NeoForge/pull/835, due to `ClientCommonPacketListenerImpl#send` and `ServerCommonPacketListenerImpl#send` having different `intermediary` and `official` names by skipping the `intermediary` and `official` remaps entirely, instead remapping straight from `mojang` to `named`.

If an alternate mapping set has the same names for both `net.minecraft.class_8673.method_52787` and `net.minecraft.class_8609.method_14364`, which Yarn does (`sendPacket`), then the remapper will be able to successfully apply the name change to the interface and everything just works.

The decompiled output might be slightly off at times, but everything will compile fine.

2024-04-23 08:46 UTC, Jab125 commented
I would like to add that the test I added only works on Java 21+, and when running on a version lower than Java 21, the test effectively skips itself.

2024-04-23 12:47 UTC, embeddedt commented
Does this have any impact on the name that vanilla lambdas get assigned?

2024-04-23 14:25 UTC, Juuxel requested changes

2024-04-23 14:25 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/util/TinyRemapperHelper.java
> +			project.getLogger().warn("Fixing records required mappings src namespace match remap src namespace, expected " + fromM + " but got " + mappingTree.getSrcNamespace() + "!");
Why is this check weakened? It's upstream code so I'd rather keep it in place.

2024-04-23 14:25 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java
Does changing the behaviour (mappings) of the final output files of MinecraftPatchedProvider corrupt existing caches/is it prone to corruption from existing caches?

I can imagine a situation where the MPP patched file exists but the named and intermediary jars get deleted, so it would try to rename `mojang -> named` even though the input file is `official`.

2024-04-23 14:25 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/providers/minecraft/MergedMinecraftProvider.java
> +		if (getExtension().isNeoForge()) return MappingsNamespace.MOJANG;
This should have a short comment about matching MinecraftPatchedProvider

2024-04-23 14:25 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/providers/minecraft/SplitMinecraftProvider.java
> +		if (getExtension().isNeoForge()) return MappingsNamespace.MOJANG;
Same here about the comment

2024-04-23 14:25 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/providers/minecraft/mapped/AbstractMappedMinecraftProvider.java
> +			project.getLogger().lifecycle(":remapping minecraft (TinyRemapper, " + fromM + " -> " + toM + ")");
```suggestion
			project.getLogger().info(":remapping minecraft (TinyRemapper, " + fromM + " -> " + toM + ")");
```
I don't think we need this log clutter back, if anything we should drop the log levels to info in some of the other cases of this

2024-04-23 14:25 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/providers/minecraft/mapped/IntermediaryMinecraftProvider.java
> +		if (extension.isNeoForge()) return MappingsNamespace.MOJANG;
I guess this making this provider a no-op? A short comment here would be good too

2024-04-23 14:25 UTC, Juuxel commented on src/test/groovy/net/fabricmc/loom/test/integration/neoforge/NeoForge1205Test.groovy
> + * Copyright (c) 2023 FabricMC
```suggestion
 * Copyright (c) 2024 FabricMC
```

2024-04-23 14:25 UTC, Juuxel commented on src/test/groovy/net/fabricmc/loom/test/integration/neoforge/NeoForge1205Test.groovy
> +		def gradle = gradleProject(project: "neoforge/12005", version: DEFAULT_GRADLE)
Nit: the project dir should be `1205` (or `1_20_5`) instead of `12005`

2024-04-23 14:25 UTC, Juuxel commented on src/test/resources/projects/neoforge/12005/build.gradle
> +		url 'https://prmaven.neoforged.net/NeoForge/pr835'
Are these PR repos future-proof? I don't want the tests to suddenly start failing 😅

2024-04-24 08:08 UTC, Kneelawk commented on src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java
This sounds like the issue I encountered when updating to this plugin.

2024-04-24 09:14 UTC, Jab125 commented on src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java
After checking, it does seem to break existing caches.

2024-04-24 09:17 UTC, Jab125 commented
> Does this have any impact on the name that vanilla lambdas get assigned?

Lambdas appear to get intermediary names, such as `method_55608`

2024-04-24 13:43 UTC, Jab125 commented
The test may need to be special cased to only run on Java 21.

2024-04-24 17:01 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java
I think adding a suffix to the patched file would be best then. (Also, is the `mojang -> mojang` rename step really needed? I'm not sure off the top of my head if the fixers are actually useful for MC 1.20.x)

2024-04-28 08:19 UTC, Jab125 commented on src/main/java/net/fabricmc/loom/util/TinyRemapperHelper.java
> +			project.getLogger().warn("Fixing records required mappings src namespace match remap src namespace, expected " + fromM + " but got " + mappingTree.getSrcNamespace() + "!");
Mapping src no longer matches remap src on NeoForge, due to the Mojmap to named remapping

2024-04-28 08:20 UTC, Jab125 commented on src/main/java/net/fabricmc/loom/util/TinyRemapperHelper.java
> +			project.getLogger().warn("Fixing records required mappings src namespace match remap src namespace, expected " + fromM + " but got " + mappingTree.getSrcNamespace() + "!");
i could change this so it only throws on non-NeoForge platforms

2024-04-28 08:20 UTC, Jab125 commented on src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java
I did a `mojang -> mojang` remap due to not wanting to manually merge multiple jars together

2024-04-28 08:21 UTC, Jab125 commented on src/main/java/net/fabricmc/loom/configuration/providers/minecraft/mapped/AbstractMappedMinecraftProvider.java
> +			project.getLogger().lifecycle(":remapping minecraft (TinyRemapper, " + fromM + " -> " + toM + ")");
I was doing this for debugging earlier, I'll drop it down to info

2024-04-28 13:44 UTC, Jab125 commented on src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java
> Does changing the behaviour (mappings) of the final output files of MinecraftPatchedProvider corrupt existing caches/is it prone to corruption from existing caches?
> 
> I can imagine a situation where the MPP patched file exists but the named and intermediary jars get deleted, so it would try to rename `mojang -> named` even though the input file is `official`.

A suffix is added to jar files now.

2024-04-30 00:15 UTC, Shadows-of-Fire commented on src/test/resources/projects/neoforge/12005/build.gradle
> +		url 'https://prmaven.neoforged.net/NeoForge/pr835'
The relevant commit is now live in NeoForge `20.6.3-beta`, so use of the PR-publish repo shouldn't be necessary

2024-05-02 06:22 UTC, closed without merging

2024-05-02 06:22 UTC, Jab125 commented
Superseded by #209