Support JarJar
architectury/architectury-loom pull request #93
Opened 2022-07-07 09:55 UTC by shedaniel

Close #92

We are waiting of https://github.com/MinecraftForge/MinecraftForge/pull/8822

This is more changes than I would have liked, but the system requires the maven notation and the version.
The version range is generated from `[VERSION,)`, which is VERSION or above. This should be very straight forward.

Adding a dependency for nesting has the same syntax as Fabric:
```groovy
include "group:module:version"
```

Signed-off-by: shedaniel <daniel@shedaniel.me>

2022-07-10 11:04 UTC, shedaniel commented
We are now waiting for https://github.com/MinecraftForge/MinecraftForge/issues/8843

2022-07-17 14:52 UTC, ThatGravyBoat commented
Any update on this as the issue in forge has been fixed.

2022-07-17 16:51 UTC, Juuxel requested changes

2022-07-17 16:51 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/build/nesting/IncludedJarFactory.java
> +				Set<Task> tasks = (Set<Task>) dependencies.getDependencies(task);
Should be `new HashSet<>(...)`

2022-07-17 16:51 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/build/nesting/JarNester.java
> +	private static void handleForgeJarJar(Collection<File> jars, List<Pair<IncludedJarFactory.Metadata, File>> forgeJars, File modJar, Logger logger) throws IOException {
Probably shouldn't take the plain jars collection, doesn't seem to be used

2022-07-17 17:05 UTC, Juuxel approved these changes

2022-07-17 17:09 UTC, merged